fix for: Incorrect `sh` determination for `system()`? #59
benhoyt/goawk pull request #64
Opened 2021-09-08 11:34 UTC by xonixx

Attempt at fixing #59.

I checked the test suit (`go test ./... -v`) - seems all green.
1. Though I feel would be good to add some more tests for this specific case, but I'm a bit unsure how exactly. The test suit in `interp_test.go` doen't have means for provinding environment variables to test. Would be glad for an advice.
2. Hopefully I changed `sh` -> `/bin/sh` in all relevant places (to cover `system()`, `"cmd" | getline`, `print | "cmd"`). But now it feels like a bit of copy-paste. Do you think it makes sense to do something about this - like extracting a function or a constant? If yes, my concern is - what is better place for it, since the change is in two files, but it doesn't feel right to complicate things much for little reason.

2021-09-09 00:27 UTC, benhoyt commented
Thanks for this. It's a good start, though I think we should make a few improvements:

* As mentioned in #59, while we're at it I think we should make this configurable via `interp.Config`. Let's add a new field `ExecCommand []string`, which if nil, defaults to `[]string{"/bin/sh", "-c"}` on Unix, and `[]string{"sh", "-c"}` on Windows.
* Setting the Windows default to just "sh" without the /bin path will make it keep working as it does today on Windows. See the unit test failures on Windows: https://github.com/benhoyt/goawk/pull/64/checks?check_run_id=3550794167
* I'm open to other names for this config field too. `ExecArgs`?
* With the new field, we will need a couple of additional tests for it. Probably a new `TestExecCommand` function in `interp/interp_test.go`. See for example https://github.com/benhoyt/goawk/blob/0eb3f8c8b7889fe1feff86aed767dcdb30cbc98e/interp/interp_test.go#L1014

2021-09-10 17:06 UTC, xonixx commented
First things first I'm totaly agree with your arguments and I'm ready to do the changes you request.

However please find couple of considerations below.

Regarding failing on Windows. 
Just did a quick check https://github.com/xonixx/playground/runs/3568823431?check_suite_focus=true#step:3:8
I see that on Win this uses sh.exe bundled with Git, which is pre-bundled into Windows environment on Github (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md). 
Therefore I assume on clean windows (no Git) goawk will fail on `system()` as well.

Does it make sense to specify in docs that on Windows the `system()` functionality of goawk is only available when Git or msys (or other sh.exe provider) is installed?

Also does it make sense to not be Windows-specific but rather go more generic approach and implement the adaptive logic to attempt both
- `/bin/sh` as POSIX require
- `sh` from `$PATH` if above fails

@benhoyt if you think it doesn't make sense to go this deep I'm totally fine just to do as you already prosposed.

2021-09-11 01:29 UTC, benhoyt commented
It's a good point regarding "sh" only existing on Windows due to Git. However, I'd rather not do a system call in every ExecProgram call due to the cost of hitting the file system (I know some use that in a fairly tight loop). So for now let's do what I suggested, and I can clean up the Windows shell 
handling in a subsequent commit (maybe "cmd.exe").

2021-09-11 20:39 UTC, benhoyt requested changes
Looks good, thanks! Just a couple of style nits.

2021-09-11 20:39 UTC, benhoyt commented on interp/functions.go
> +	shellArgs := p.shellCommand[1:]
Naming nit: how about we name these `executable` and `args`? We don't need the `shell` prefix in this context as this function already includes that in the name.

2021-09-11 20:39 UTC, benhoyt commented on interp/functions.go
> +// Call native-defined function with given name and arguments,
Thanks for catching. Let's make this "return its return value" like the comment on `callUser`.

2021-09-11 20:39 UTC, benhoyt commented on interp/functions.go
> +	minIn := len(f.in) // Minimum number of args we should pass
Good catch!

2021-09-11 20:39 UTC, benhoyt commented on interp/interp.go
> +		var shellInterpreter string
Nits: let's call this `executable`. Also, let's simplify slightly to:

```go
executable := "/bin/sh"
if runtime.GOOS == "windows" {
    executable = "sh"
}
```

2021-09-11 20:39 UTC, benhoyt commented on interp/interp_test.go
> +	}
Nice, thanks for adding a test!

For a Windows test, it [looks like](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd) we might be able to test with `config.ShellCommand = []string{"cmd.exe", "/c"}` ... though I'm not quite sure what would be a good, Windows-only command to run. Feel free to leave that out.

2021-09-11 21:20 UTC, xonixx commented
@benhoyt Hopefully I fixed all CR notes

2021-09-11 22:12 UTC, merged

2021-09-11 22:12 UTC, benhoyt commented
Thanks, looks good!